### ISSUE TITLE
when rebuild project I get error TS6059

### ISSUE THREAD

**Issue by jmptrader** [trebco/treb#1]
Hi, 

I'm trying to add some improvements and tweaks that I will potentially propose as a pull request.

But when trying to rebuild the project with the changes.

I get a lot of errors like TS6059 and TS6307.

I tried Arrange directories having succeeded with some scripts but not everything works correctly.

In particular, I'd like to run an 'npm run release' .

There are some considerations to take into account: variable setting, npm/node/typescript versions.

I am working on windows.

Any comments, I appreciate it.

Thank you so much.

**Comment by duncanwerner** [comment]
Are you building on Windows proper or WSL? Can you tell me the version of node you are using? I'll try a build and see if I can duplicate the errors.

**Comment by jmptrader** [comment]
I'm building on Windows.
```

	Microsoft Windows 10 Pro
	10.0.19044 N/D Compilation 19044
	64bits


	npm -v
	9.6.7

	node -v
	v18.15.0

	tsc -v
	Version 5.0.4


```

Thank's for you comments.

**Comment by duncanwerner** [comment]
Try this new branch [worker-build-test](https://github.com/trebco/treb/tree/worker-build-test). I cleaned up the worker build so it works with both tsc and esbuild.

Let me know if that works for you and I will merge it into main.

**Comment by jmptrader** [comment]
I don't have any compile/build errors , it works perfectly! Thank you!

![image](https://github.com/trebco/treb/assets/580082/463bd486-6243-49de-8ccb-0b74e76e619c)

**Comment by duncanwerner** [comment]
Looks good, I merged into main (with a few other minor changes).
